package com.mycompany.p1pro3.vista;

import com.mycompany.p1pro3.Medico;
import com.mycompany.p1pro3.Persona;
import com.mycompany.p1pro3.control.Control;
import com.mycompany.p1pro3.control.TipoUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author minar
 */
public class CambioContraseña extends javax.swing.JFrame {

    /**
     * Creates new form CambioContraseña
     */
    public CambioContraseña(Control ControlPrincipal) {
        this.controlador = ControlPrincipal;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Cedula = new javax.swing.JLabel();
        Clave = new javax.swing.JLabel();
        txtclaveAnterior = new javax.swing.JPasswordField();
        txtCedula = new javax.swing.JTextField();
        btnCambiar = new javax.swing.JButton();
        Clave1 = new javax.swing.JLabel();
        txtclaveNueva = new javax.swing.JPasswordField();
        lblmensaje = new javax.swing.JLabel();
        btnCambiar1 = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Cedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cedula.setText("Cedula: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(133, 107, 0, 0);
        getContentPane().add(Cedula, gridBagConstraints);

        Clave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Clave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Clave.setText("Clave Anterior: ");
        Clave.setAlignmentX(0.25F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 95, 0, 0);
        getContentPane().add(Clave, gridBagConstraints);

        txtclaveAnterior.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtclaveAnterior.setPreferredSize(new java.awt.Dimension(90, 22));
        txtclaveAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclaveAnteriorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 1, 0, 142);
        getContentPane().add(txtclaveAnterior, gridBagConstraints);

        txtCedula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCedula.setPreferredSize(new java.awt.Dimension(90, 22));
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(133, 1, 0, 142);
        getContentPane().add(txtCedula, gridBagConstraints);

        btnCambiar.setText("Cambiar");
        btnCambiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCambiar.setMargin(new java.awt.Insets(2, 19, 3, 14));
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 46, 0, 0);
        getContentPane().add(btnCambiar, gridBagConstraints);

        Clave1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Clave1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Clave1.setText("Clave Nueva: ");
        Clave1.setAlignmentX(0.25F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 95, 0, 0);
        getContentPane().add(Clave1, gridBagConstraints);

        txtclaveNueva.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtclaveNueva.setPreferredSize(new java.awt.Dimension(90, 22));
        txtclaveNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclaveNuevaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 1, 0, 142);
        getContentPane().add(txtclaveNueva, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(lblmensaje, gridBagConstraints);

        btnCambiar1.setText("Cambiar");
        btnCambiar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCambiar1.setMargin(new java.awt.Insets(2, 19, 3, 14));
        btnCambiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 46, 0, 0);
        getContentPane().add(btnCambiar1, gridBagConstraints);

        Regresar.setText("Regresar");
        Regresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Regresar.setMargin(new java.awt.Insets(2, 19, 3, 14));
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 46, 75, 0);
        getContentPane().add(Regresar, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtclaveAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclaveAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclaveAnteriorActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed

        String cedula = txtCedula.getText().trim();
        String claveAnterior = new String(txtclaveAnterior.getPassword());
        String nuevaClave = new String(txtclaveNueva.getPassword());

        Persona persona = controlador.validarUsuario(cedula, claveAnterior); // usa el login del GestorPersonas
//        TipoUsuario tipo = controlador.tipoDeUsuario(persona);

        if (nuevaClave.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La nueva clave no puede estar vacía");
            return;
        }
        
        if (persona != null) {
            if (claveAnterior.equals(persona.getClave()) && !nuevaClave.equals(persona.getClave())) {
                persona.setClave(nuevaClave);
                controlador.GuardarCambioContraseña();
                
                JOptionPane.showMessageDialog(this, "Contraseña cambiada con éxito");
                return;
            } else {
                JOptionPane.showMessageDialog(this, "La clave es la misma que la anterior");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecta");
            return;
        }
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void txtclaveNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclaveNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclaveNuevaActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btnCambiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiar1ActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
       // Abrir la ventana de Login
        Login login = new Login(controlador); // le paso el mismo controlador
        login.setVisible(true);

        //cerrar la ventana principal si no la necesitás abierta
        this.dispose(); //cerramos ventanaPrincipal
    }//GEN-LAST:event_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambioContraseña(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cedula;
    private javax.swing.JLabel Clave;
    private javax.swing.JLabel Clave1;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnCambiar1;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtclaveAnterior;
    private javax.swing.JPasswordField txtclaveNueva;
    // End of variables declaration//GEN-END:variables

    private final Control controlador;

}
