
package com.mycompany.p1pro3.vista;

import com.mycompany.p1pro3.Medico;
import com.mycompany.p1pro3.Persona;
import com.mycompany.p1pro3.control.Control;
import com.mycompany.p1pro3.control.TipoUsuario;

/**
 *
 * @author minar
 */
public class CambioContraseña extends javax.swing.JFrame {

    /**
     * Creates new form CambioContraseña
     */
    public CambioContraseña(Control ControlPrincipal) {
        this.controlador= ControlPrincipal;
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Cedula = new javax.swing.JLabel();
        Clave = new javax.swing.JLabel();
        txtclave = new javax.swing.JPasswordField();
        txtCedula = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        Clave1 = new javax.swing.JLabel();
        txtclave1 = new javax.swing.JPasswordField();
        lblmensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Cedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cedula.setText("Cedula: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(133, 107, 0, 0);
        getContentPane().add(Cedula, gridBagConstraints);

        Clave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Clave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Clave.setText("Clave Anterior: ");
        Clave.setAlignmentX(0.25F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 95, 0, 0);
        getContentPane().add(Clave, gridBagConstraints);

        txtclave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtclave.setPreferredSize(new java.awt.Dimension(90, 22));
        txtclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 1, 0, 142);
        getContentPane().add(txtclave, gridBagConstraints);

        txtCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCedula.setPreferredSize(new java.awt.Dimension(90, 22));
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(133, 1, 0, 142);
        getContentPane().add(txtCedula, gridBagConstraints);

        btnLogin.setText("Cambiar");
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setMargin(new java.awt.Insets(2, 19, 3, 14));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 46, 104, 0);
        getContentPane().add(btnLogin, gridBagConstraints);

        Clave1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Clave1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Clave1.setText("Clave Nueva: ");
        Clave1.setAlignmentX(0.25F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 95, 0, 0);
        getContentPane().add(Clave1, gridBagConstraints);

        txtclave1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtclave1.setPreferredSize(new java.awt.Dimension(90, 22));
        txtclave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclave1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 1, 0, 142);
        getContentPane().add(txtclave1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(lblmensaje, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclaveActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        String cedula = txtCedula.getText();
        String clave = new String(txtclave.getPassword());

        Persona persona = controlador.validarUsuario(cedula, clave); // usa el login del GestorPersonas
        TipoUsuario tipo = controlador.tipoDeUsuario(persona);

        if (persona != null && tipo == TipoUsuario.MEDICO) {
            controlador.abrirVentanaMedico((Medico) persona); // abre la ventana correcta
            this.dispose(); // cierra la ventana de login
        }
        if (tipo != null) {
            controlador.abrirVentanaSegunUsuario(tipo);
            this.dispose();
        } else {
            lblmensaje.setText("Usuario o clave incorrectos");
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtclave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclave1ActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambioContraseña(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cedula;
    private javax.swing.JLabel Clave;
    private javax.swing.JLabel Clave1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtclave;
    private javax.swing.JPasswordField txtclave1;
    // End of variables declaration//GEN-END:variables

private final Control controlador;
}
