
package com.mycompany.p1pro3.vista;

import com.mycompany.p1pro3.Medico;
import com.mycompany.p1pro3.Persona;
import com.mycompany.p1pro3.control.TipoUsuario;
import com.mycompany.p1pro3.control.Control;
import javax.swing.SwingConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.kordamp.ikonli.fontawesome.FontAwesome;
import org.kordamp.ikonli.swing.FontIcon;


public class Login extends javax.swing.JFrame {

    
    public Login(Control ControlPrincipal) {
         this.controlador= ControlPrincipal;
//         this.estado = new FormHandler();
        initComponents();
        this.setLocationRelativeTo(null);
        init();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Cedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        Clave = new javax.swing.JLabel();
        BotonLogin = new javax.swing.JButton();
        lblmensaje = new javax.swing.JLabel();
        txtclave = new javax.swing.JPasswordField();
        BotonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Cedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cedula.setText("Cedula: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(117, 115, 0, 0);
        getContentPane().add(Cedula, gridBagConstraints);

        txtCedula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCedula.setPreferredSize(new java.awt.Dimension(90, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 244;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(117, 12, 0, 158);
        getContentPane().add(txtCedula, gridBagConstraints);

        Clave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Clave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Clave.setText("Clave: ");
        Clave.setAlignmentX(0.25F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 120, 0, 0);
        getContentPane().add(Clave, gridBagConstraints);

        BotonLogin.setText("Ingresar");
        BotonLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonLogin.setMargin(new java.awt.Insets(2, 19, 3, 14));
        BotonLogin.setMaximumSize(new java.awt.Dimension(64, 33));
        BotonLogin.setMinimumSize(new java.awt.Dimension(64, 26));
        BotonLogin.setPreferredSize(new java.awt.Dimension(60, 33));
        BotonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 12, 139, 0);
        getContentPane().add(BotonLogin, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(lblmensaje, gridBagConstraints);

        txtclave.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtclave.setPreferredSize(new java.awt.Dimension(90, 22));
        txtclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 244;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 158);
        getContentPane().add(txtclave, gridBagConstraints);

        BotonVolver.setText("Regresar");
        BotonVolver.setPreferredSize(new java.awt.Dimension(60, 33));
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 37, 139, 158);
        getContentPane().add(BotonVolver, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLoginActionPerformed

        String cedula = txtCedula.getText().trim();
        String clave = new String(txtclave.getPassword()).trim();

        Persona persona = controlador.validarUsuario(cedula, clave); // usa el login del GestorPersonas
        TipoUsuario tipo = controlador.tipoDeUsuario(persona);
        
        if (persona != null && tipo == TipoUsuario.MEDICO) {
            controlador.abrirVentanaMedico((Medico) persona); // abre la ventana correcta
            this.dispose(); // cierra la ventana de login
        }
        if (tipo != null) {
            controlador.abrirVentanaSegunUsuario(tipo);
            this.dispose();
        } else {
            lblmensaje.setText("Usuario o clave incorrectos");
        }
      
    }//GEN-LAST:event_BotonLoginActionPerformed

    private void txtclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclaveActionPerformed
         BotonLogin.doClick();
    }//GEN-LAST:event_txtclaveActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        controlador.volverVentanaPrincipal();
        
    }//GEN-LAST:event_BotonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf look and feel */
        try {
            //javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
            // Si prefieres oscuro:
             javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatDarkLaf());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Login.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login(null).setVisible(true);
            }
        });
    }
    
    public void init(){
         // Inicialmente, oculta los puntos.
        txtclave.setEchoChar((char) 0);
        txtclave.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                if (txtclave.getPassword().length > 0) {
                    txtclave.setEchoChar('*');
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if (txtclave.getPassword().length == 0) {
                    txtclave.setEchoChar((char) 0);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                //indicarCambios(); // no lo hemos usado
            }
        });
        configuracionIconosBotones();
    }

    public void configuracionIconosBotones(){
        // Tamaño deseado para los iconos
        int tamañoIcono = 24; // 24px es un tamaño estándar

        // Botón Ingresar
        BotonLogin.setIcon(FontIcon.of(FontAwesome.CHECK, tamañoIcono)); // icono de llave
        BotonLogin.setHorizontalTextPosition(SwingConstants.RIGHT);
        BotonLogin.setVerticalTextPosition(SwingConstants.CENTER);
        BotonLogin.setIconTextGap(8);
        BotonLogin.setHorizontalAlignment(SwingConstants.LEFT);

        // Botón Regresar
        BotonVolver.setIcon(FontIcon.of(FontAwesome.ARROW_LEFT, tamañoIcono));
        BotonVolver.setHorizontalTextPosition(SwingConstants.RIGHT);
        BotonVolver.setVerticalTextPosition(SwingConstants.CENTER);
        BotonVolver.setIconTextGap(8);
        BotonVolver.setHorizontalAlignment(SwingConstants.LEFT);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonLogin;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JLabel Cedula;
    private javax.swing.JLabel Clave;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtclave;
    // End of variables declaration//GEN-END:variables

private final Control controlador;

}

