
package com.mycompany.p1pro3.vista;

import com.mycompany.p1pro3.Medico;
import com.mycompany.p1pro3.Persona;
import com.mycompany.p1pro3.control.TipoUsuario;
import com.mycompany.p1pro3.control.Control;
import cr.ac.una.gui.FormHandler;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;


public class Login extends javax.swing.JFrame {

    
    public Login(Control ControlPrincipal) {
         this.controlador= ControlPrincipal;
//         this.estado = new FormHandler();
        initComponents();
        this.setLocationRelativeTo(null);
        init();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Cedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        Clave = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblmensaje = new javax.swing.JLabel();
        txtclave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Cedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cedula.setText("Cedula: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(69, 40, 0, 0);
        getContentPane().add(Cedula, gridBagConstraints);

        txtCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCedula.setPreferredSize(new java.awt.Dimension(90, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 96;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(69, 12, 0, 132);
        getContentPane().add(txtCedula, gridBagConstraints);

        Clave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Clave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Clave.setText("Clave: ");
        Clave.setAlignmentX(0.25F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 45, 0, 0);
        getContentPane().add(Clave, gridBagConstraints);

        btnLogin.setText("Ingresar");
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setMargin(new java.awt.Insets(2, 19, 3, 14));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 53, 0, 0);
        getContentPane().add(btnLogin, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 88, 132);
        getContentPane().add(lblmensaje, gridBagConstraints);

        txtclave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtclave.setPreferredSize(new java.awt.Dimension(90, 22));
        txtclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 96;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 132);
        getContentPane().add(txtclave, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        String cedula = txtCedula.getText();
        String clave = new String(txtclave.getPassword());

        Persona persona = controlador.validarUsuario(cedula, clave); // usa el login del GestorPersonas
        TipoUsuario tipo = controlador.tipoDeUsuario(persona);
        
        if (persona != null && tipo == TipoUsuario.MEDICO) {
            controlador.abrirVentanaMedico((Medico) persona); // abre la ventana correcta
            this.dispose(); // cierra la ventana de login
        }
        if (tipo != null) {
            controlador.abrirVentanaSegunUsuario(tipo);
            this.dispose();
        } else {
            lblmensaje.setText("Usuario o clave incorrectos");
        }
      
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login(null).setVisible(true);
            }
        });
    }
    
    public void init(){
         // Inicialmente, oculta los puntos.
        txtclave.setEchoChar((char) 0);
        
        
        txtclave.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                if (txtclave.getPassword().length > 0) {
                    txtclave.setEchoChar('*');
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if (txtclave.getPassword().length == 0) {
                    txtclave.setEchoChar((char) 0);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                //indicarCambios(); // no lo hemos usado
            }

        });
    
    
    }
//    private void indicarCambios() {
////        estado.setModified(true);
//        actualizarControles();
//    }
//    
//    private void actualizarControles(){
//    
//    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cedula;
    private javax.swing.JLabel Clave;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtclave;
    // End of variables declaration//GEN-END:variables

private final Control controlador;
//private FormHandler estado;
}

