package com.mycompany.p1pro3.vista;

import com.mycompany.p1pro3.control.control;
import com.mycompany.p1pro3.modelo.modelo;


public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     * @param controlador
     */
    public VentanaPrincipal(control controlador) {
        this.controlador = controlador; //El controlador es la conexion entre la ventana
        initComponents();               // y los metodos del controlador
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        BotonLogin = new javax.swing.JButton();
        BotonPassword = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(450, 350));

        jPanel1.setMinimumSize(new java.awt.Dimension(250, 150));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        label1.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        label1.setText("Sistema hospitalario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        jPanel1.add(label1, gridBagConstraints);

        BotonLogin.setText("Log In");
        BotonLogin.setMaximumSize(new java.awt.Dimension(146, 124));
        BotonLogin.setMinimumSize(new java.awt.Dimension(146, 124));
        BotonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonLoginMouseClicked(evt);
            }
        });
        BotonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel1.add(BotonLogin, gridBagConstraints);

        BotonPassword.setText("Change Password");
        BotonPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonPassword.setMaximumSize(new java.awt.Dimension(156, 124));
        BotonPassword.setMinimumSize(new java.awt.Dimension(156, 124));
        BotonPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel1.add(BotonPassword, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonLoginMouseClicked

    private void BotonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLoginActionPerformed

         // Abrir la ventana de Login
        Login login = new Login(controlador); // le paso el mismo controlador
        login.setVisible(true);

        //cerrar la ventana principal si no la necesitás abierta
        this.dispose(); //cerramos ventanaPrincipal
    }//GEN-LAST:event_BotonLoginActionPerformed

    private void BotonPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        modelo modelo = new modelo();              // Modelo
        control controlador = new control(modelo); // Controlador

        java.awt.EventQueue.invokeLater(() -> {
            new VentanaPrincipal(controlador).setVisible(true); // Vista principal
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonLogin;
    private javax.swing.JButton BotonPassword;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
//private control control; // le añadimos un control
    private final control controlador;
}
