package com.mycompany.p1pro3.vista;

import com.mycompany.p1pro3.Medico;
import com.mycompany.p1pro3.Persona;
import com.mycompany.p1pro3.control.TipoUsuario;
import com.mycompany.p1pro3.control.Control;
import javax.swing.SwingConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.kordamp.ikonli.fontawesome.FontAwesome;
import org.kordamp.ikonli.swing.FontIcon;
/* -------------------------------------------------------------------+
*                                                                     |
* (c) 2025                                                            |
* EIF206 - Programación 3                                             |
* 2do ciclo 2025                                                      |
* NRC 51189 – Grupo 05                                                |
* Proyecto 1                                                          |
*                                                                     |
* 2-0816-0954; Avilés López, Karen Minards                            |
* 4-0232-0641; Zárate Hernández, Nicolas Alfredo                      |
*                                                                     |
* versión 1.0.0 13-09-2005                                            |
*                                                                     |
* --------------------------------------------------------------------+
*/

public class VentanaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaLogin.class.getName());

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin(Control ControlPrincipal) {
        this.controlador = ControlPrincipal;
        initComponents();
        this.setLocationRelativeTo(null);
        init();

    }
    
    public void init() {
        // Inicialmente, oculta los puntos.
        txtclave.setEchoChar((char) 0);
        txtclave.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                if (txtclave.getPassword().length > 0) {
                    txtclave.setEchoChar('*');
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if (txtclave.getPassword().length == 0) {
                    txtclave.setEchoChar((char) 0);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                //indicarCambios(); // no lo hemos usado
            }
        });
        configuracionIconosBotones();
    }

    public void configuracionIconosBotones() {
        // Tamaño deseado para los iconos
        int tamañoIcono = 20; // 24px es un tamaño estándar

        // Botón Ingresar
        BotonLogin.setIcon(FontIcon.of(FontAwesome.CHECK, tamañoIcono)); // icono de llave
        BotonLogin.setHorizontalTextPosition(SwingConstants.RIGHT);
        BotonLogin.setVerticalTextPosition(SwingConstants.CENTER);
        BotonLogin.setIconTextGap(8);
        BotonLogin.setHorizontalAlignment(SwingConstants.LEFT);

        // Botón Regresar
        BotonVolver.setIcon(FontIcon.of(FontAwesome.ARROW_LEFT, tamañoIcono));
        BotonVolver.setHorizontalTextPosition(SwingConstants.RIGHT);
        BotonVolver.setVerticalTextPosition(SwingConstants.CENTER);
        BotonVolver.setIconTextGap(8);
        BotonVolver.setHorizontalAlignment(SwingConstants.LEFT);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cedula = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        textCedula = new javax.swing.JTextField();
        BotonLogin = new javax.swing.JButton();
        BotonVolver = new javax.swing.JButton();
        txtclave = new javax.swing.JPasswordField();
        lblmensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Cedula.setText("Cédula:");

        Contraseña.setText("Contraseña:");

        BotonLogin.setText("Ingresar");
        BotonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLoginActionPerformed(evt);
            }
        });

        BotonVolver.setText("Regresar");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Contraseña)
                            .addComponent(Cedula))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCedula)
                            .addComponent(txtclave)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(lblmensaje)
                        .addGap(0, 142, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(239, 239, 239))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cedula)
                    .addComponent(textCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Contraseña))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(BotonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addComponent(lblmensaje)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLoginActionPerformed
        // TODO add your handling code here:
        String cedula = textCedula.getText().trim();
        String clave = new String(txtclave.getPassword()).trim();

        Persona persona = controlador.validarUsuario(cedula, clave); // usa el login del GestorPersonas
        TipoUsuario tipo = controlador.tipoDeUsuario(persona);

        if (persona != null && tipo == TipoUsuario.MEDICO) {
            controlador.abrirVentanaMedico((Medico) persona); // abre la ventana correcta
            this.dispose(); // cierra la ventana de login
        }
        if (tipo != null) {
            controlador.abrirVentanaSegunUsuario(tipo);
            this.dispose();
        } else {
            lblmensaje.setText("Usuario o clave incorrectos");
        }
    }//GEN-LAST:event_BotonLoginActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        controlador.volverVentanaPrincipal();
    }//GEN-LAST:event_BotonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            //javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
            // Si prefieres oscuro:
            javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatDarkLaf());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonLogin;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JLabel Cedula;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JTextField textCedula;
    private javax.swing.JPasswordField txtclave;
    // End of variables declaration//GEN-END:variables

private final Control controlador;
}
